// File: Greatest_common_divisor.v
// Generated by MyHDL 0.11
// Date: Wed Nov 23 15:08:12 2022


`timescale 1ns/10ps

module Greatest_common_divisor (
    start,
    a,
    b,
    clk,
    rst_n,
    gcd,
    done
);


input start;
input [15:0] a;
input [15:0] b;
input clk;
input rst_n;
output [15:0] gcd;
reg [15:0] gcd;
output done;
reg done;

reg [15:0] A;
reg [15:0] B;
reg [1:0] state;



always @(posedge clk) begin: GREATEST_COMMON_DIVISOR_LOGIC
    if (rst_n == 0) begin
        gcd <= 0;
        B <= 0;
        A <= 0;
        state <= 0;
        done <= 0;
    end
    else begin
        case (state)
            'h0: begin
                gcd <= 0;
                done <= 0;
                if ((start == 1)) begin
                    state <= 1;
                    A <= a;
                    B <= b;
                end
                else begin
                    state <= 0;
                end
            end
            'h1: begin
                gcd <= 0;
                done <= 0;
                if ((A == 0)) begin
                    state <= 2;
                    done <= 1;
                    gcd <= B;
                end
                else begin
                    if ((B == 0)) begin
                        state <= 2;
                        done <= 1;
                        gcd <= A;
                    end
                    else begin
                        state <= 2;
                        if ((A > B)) begin
                            A <= (A - B);
                        end
                        else begin
                            B <= (B - A);
                        end
                    end
                end
            end
            'h2: begin
                state <= 3;
            end
            'h3: begin
                state <= 0;
            end
        endcase
    end
end

endmodule
